'''
Created on 10 ago. 2017

@author: Val
'''
NO_VALID_TOKEN = "The token provided is not correct, check https://www.geni.com/platform/developer/api_explorer to get a valid token"
#Requests errors
ERROR_REQUESTS = "Error obtained from Geni when using API with the following message = "

ABOUT_ME_MESSAGE = "Profile automatically generated by [https://github.com/Thimxx/pyGenealogical-Tools pyGenealogical-Tools] using reference(s) : "
RESIDENCE_MESSAGE = "\nResidence data obtained: "
NO_VALID_UNION_PROFILE = "The provided profile does not contain a single union it contains the following number of unions: "

#gedcom
NUMBER_OF_PROFILES = "Total number of added profiles = "
PROCESSING = " processing == "