'''
Created on 15 oct. 2019

@author: Val
'''

RESEARCH_LOG = "pyGenealogicalTools"
RESEARCH_INFO = "Research Log automatically generated by pyGenealogicalTools as tracking and storing of obtained results of automatic search"